[package]
name = "katex"
version = "0.4.0-alpha.3"
authors = ["Cheng XU <rust@xuc.me>"]
edition = "2018"
license = "MIT OR Apache-2.0"
description = "Rust bindings to KaTeX"
repository = "https://github.com/xu-cheng/katex-rs"
documentation = "https://docs.rs/katex"
readme = "README.md"
keywords = ["LaTeX", "KaTeX", "Math"]
categories = ["api-bindings"]

[dependencies]
cfg-if = "1.0"
derive_builder = "0.10"
itertools = "0.10"
thiserror = "1.0"

# quick-js is available in unix and x86_64-pc-windows-gnu
[target.'cfg(any(unix, all(windows, target_env = "gnu")))'.dependencies]
quick-js = { version = "0.4", features = ["patched"], optional = true }

# duktape is available in unix and windows
[target.'cfg(any(unix, windows))'.dependencies]
ducc = { version = "0.1", optional = true }

[features]
default = ["quick-js"]
duktape = ["ducc"]
