[package]
name = "katex"
version = "0.2.0"
authors = ["Cheng XU <rust@xuc.me>"]
edition = "2018"
license = "MIT OR Apache-2.0"
description = "Rust bindings to KaTeX"
repository = "https://github.com/xu-cheng/katex-rs"
documentation = "https://docs.rs/katex"
readme = "README.md"
keywords = ["LaTeX", "KaTeX", "Math"]
categories = ["api-bindings"]

[dependencies]
derive_builder = "0.9.0"
quick-js = "0.3.0"
thiserror = "1.0"
