name: clippy
on: [push, pull_request]
jobs:
  clippy:
    name: clippy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        features: ["quick-js", "ducktape"]
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Set up rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: clippy
      - name: Run clippy
        uses: actions-rs/clippy-check@v1
        with:
          name: clippy-${{ matrix.features }}
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --no-default-features --features ${{ matrix.features }} --all-targets -- -D warnings

